### ISSUE TITLE
Fetch the SSH Host Key from the Meta API

### ISSUE THREAD

**Issue by EricRibeiro** [CircleCI-Public/github-cli-orb#25]
## Describe Request:

Recently GitHub included the SSH host keys in the [meta API request](https://github.blog/changelog/2022-01-18-githubs-ssh-host-keys-are-now-published-in-the-api/). The orb should use it to fetch the `rsa` key instead of [hardcoding](https://github.com/CircleCI-Public/github-cli-orb/blob/main/src/scripts/clone.sh#L3) it.

## Examples:

GitHub:
```
 curl \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/meta
```

GitHub Enterprise:
```
 curl \
  -H "Accept: application/vnd.github.v3+json" \
  http(s)://{hostname}/api/v3/meta
```

## Supporting Documentation Links:

https://github.blog/changelog/2022-01-18-githubs-ssh-host-keys-are-now-published-in-the-api/
https://docs.github.com/en/rest/reference/meta#get-github-meta-information
https://api.github.com/meta
https://docs.github.com/en/enterprise-server@3.2/rest/reference/meta

**Comment by motionsuggests** [comment]
Thanks this is great because I needed to solve this to work with our GitHub enterprise server.

**Comment by EricRibeiro** [comment]
@motionsuggests, I was planning on tackling this issue in a couple of weeks, but I saw that you made Enterprise-related contributions to this orb in the past. 

I wonder if you are up to pushing a PR with the feature? If so, we can fast-track and get it out of our way.

**Comment by motionsuggests** [comment]
@EricRibeiro I apologize for not responding earlier. It's been a hell of month. Hopefully I will take a shot at it next week.

**Comment by KyleTryon** [comment]
Just opened #25, this should cover it.
