### ISSUE TITLE
Setup command fails in the absence of `read:org` scope

### ISSUE THREAD

**Issue by jsab** [CircleCI-Public/github-cli-orb#30]
## Orb version:

2.1.0

## What happened:

When using the `setup` command with a token that does not have the `read:org` scope, the setup fails needlessly.

## Expected behavior:

Setup should succeed with any token.

## Additional Information:

This is caused by the `gh auth status` command and I will submit a PR in a few minutes.

**Comment by KyleTryon** [comment]
Hello @jsab 

Thank you for submitting your issue with a PR. I need to ask why we want to accept a token without the ability to run the `status` command. Currently we take advantage of this fact to test the orb and make sure it is installing and configuring correctly.

Is there are use-case where you want to run the setup command without authenticating? Authenticating but with a scope not covered here?

In what scenario would this be preferable to running the `install` command without running `setup`?

**Comment by jsab** [comment]
Hi @KyleTryon,

> I need to ask why we want to accept a token without the ability to run the status command.

A token can have many scopes. In the context of a CI job, the `repo` scope will allow the token to clone, look at PRs, comment and even push commits. In many cases, nothing else is required for proper job execution. Thus, in accordance with the principle of least privilege, nothing else should be granted.

> Is there are use-case where you want to run the setup command without authenticating?

This issue and the accompanying PR is not concerned with the authentication step, only the debug/validation output of the setup.

> Authenticating but with a scope not covered here?

Yes, authenticating with the `repo` scope and not the `read:org` scope which is not needed.

> In what scenario would this be preferable to running the install command without running setup?

The authentication is still happening. Any scope is valid for authenticating.
