### ISSUE TITLE
Using a `checkout` step in a job breaks usage of `gh repo clone`

### ISSUE THREAD

**Issue by jsab** [CircleCI-Public/github-cli-orb#32]
## Orb version:

2.1.0

## What happened:

If you use a checkout step in your job, for example:
```
    steps:
      - checkout
      - gh/setup
      - run: gh repo clone MyOrg/MyRepo
```

It will fail with the following error if the repository requires the auth from the token configured in gh/setup:
```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit status 128
```

Omitting the `checkout` step fixes the issue.

Investigation into the issue reveals that the `checkout` step creates a `~/.gitconfig` that breaks usage of `gh repo clone` by redirecting all `https://github.com` git usage to `ssh://git@github.com`. Here is the contents as created as a side-effect of `checkout`:

```
[url "ssh://git@github.com"]
	insteadOf = https://github.com
[gc]
	auto = 0
```

Since the `gh` CLI tool configures a git credential helper for https://github.com, the redirect configured by the `checkout` step renders it useless as everything is redirected to SSH thus ends up using the repository specific SSH key configured by CircleCI.

## Expected behavior:

Usage of `checkout` command should not affect usage of the `github-cli` orb. 

I would argue `checkout` should not make any modification to global git configuration. 

If there is no way around modification of the global git configuration, it should at least be specific to the repository that `checkout` will operate on instead of redirecting every github.com URL.

## Additional Information:

Other workarounds include doing your `gh repo` commands before the `checkout` step or adding a `rm ~/.gitconfig` immediately after the `checkout` step.

**Comment by KyleTryon** [comment]
Hello @jsab 
thanks for brining this up, this makes sense. We can look into this. 

We had somewhat assumed this clone command would actually be used to replace the native checkout step. Would that be a viable answer for you?

I think the way we may need to resolve this, we may consider just removing the `~/.gitconfig` as a part of setup

**Comment by jsab** [comment]
Hi @KyleTryon, 

In our case all our projects use the native `checkout` step and a few rare projects actually need to clone other repositories which they do using `gh` after the native checkout of the "main" repository.

I think the correct resolution is indeed for the checkout command not to have broad side-effects on the global git configuration of the container (if at all).

However, any resolution would be "viable" including "not a bug/won't fix" as workarounds exist such as not using the native checkout, cleaning up configuration leftovers left by it or implementing our our checkout step.

Right now, in the few cases required we do the cleanup that the checkout command does not do after running the checkout command:

```
git config --global --unset-all 'url.ssh://git@github.com.insteadof'
```

**Comment by KyleTryon** [comment]
Thank you for this information. Because there has not been any further community involvement, I am going to close this ticket as `won't do` for now. I am happy to re-open with interest. My suggestion, the native `checkout` step of CircleCI is highly opinionated but is crafted in a way to be generic enough to work for a wide range of users, platforms, and scenarios. In some cases, it is perfectly acceptable to replace the native checkout step with your own `git` commands if the situation calls for it. Other options should be available via orbs with less configuration needed, such as this orb's `gh/clone` command. There are also a few [community orbs](https://circleci.com/developer/orbs?query=git&page=1&pageSize=15) focused around git available as well.
