### ISSUE TITLE
Relese job time out: `setup` command should be called before executing `release` job

### ISSUE THREAD

**Issue by csikb** [CircleCI-Public/github-cli-orb#48]
## Orb version:

2.3.0

## What happened:

The release job will time out waiting for an interactive prompt.
```
gh config set prompt disabled
```
should be called before.

## Expected behavior:

Call the `setup` command before using the cli.

**Comment by csikb** [comment]
This could be a solution:
https://github.com/CircleCI-Public/github-cli-orb/pull/49

**Comment by csikb** [comment]
Or calling the `gh config set prompt disabled` method in the install scipt

**Comment by Unb0rn** [comment]
Any updates on this? Release job is still non-functional...

**Comment by marboledacci** [comment]
#49 was merged an released, if that fixed the problem please close the issue, otherwise provide more details.
