### ISSUE TITLE
Can't upload binaries compiled in previous jobs, as cloning step fails due to directory not being empty

### ISSUE THREAD

**Issue by ConorHartin** [CircleCI-Public/github-cli-orb#55]
## Orb version:
circleci/github-cli@2.3.0

## What happened:
I am running pyinstaller in both windows & linux executors, and persisting the namespace containing the output of those jobs so it will be available in the github-cli orb so I can upload those files specifically. If I attach that namespace to the upload job, then it never gets to the upload command because the clone command fails due to the "." directory not being empty. If I run pre-steps commands to create a tmp folder and cd into that, it just gets ignored and the orb's clone command (which I don't actually need to run, as I already cloned the repo in question in order to run pyinstaller on it to generate the files I actually want to upload) runs from the default directory. There doesn't seem to be a way to set the working_directory of an orb job as far as I can tell. It's possible this is not a limitation of the orb and I'm just not configuring it correctly, but I currently don't see a way to configure it to do that.
I also tried running the release job, but that always times out on CircleCI, appearing to hang indefinitely.

## Expected behavior:

To be able to upload files created outside the githhub-cli orb.

**Comment by marboledacci** [comment]
I see two problems here, the clone step on upload and release is mandatory, which causes conflicts when you already have the repo cloned.
Second, the release and upload job always try to clone to "." which doesn't allow you to work in a different directory.
I'm working in a solution for both now.
