### ISSUE TITLE
install command fails when downloading GH CLI 

### ISSUE THREAD

**Issue by tl-luca-baggi** [CircleCI-Public/github-cli-orb#64]
## Orb version:

2.5.0, 2.6.0

## What happened:

After upgrading orb version to `2.5.0`, `install` command started to fail with the following stacktrace:
```
Downloading the GitHub CLI from "https://github.com/cli/cli/releases/download/v/gh__linux_amd64.deb"...
Installing the GitHub CLI...
+ apt install --yes ./gh-cli.deb
Reading package lists... Error!
E: Invalid archive signature
E: Internal error, could not locate member control.tar{.zst,.lz4,.gz,.xz,.bz2,.lzma,}
E: Could not read meta data from /root/project/gh-cli.deb
E: The package lists or status file could not be parsed or opened.
+ set +x
Something went wrong installing the GH CLI. Please try again or open an issue.

Exited with code exit status 1
```

The issue seems to be related to this piece of code:
```
download_gh_cli() {
    local platform=$1
    local file_extension=$2
    if [ "$PARAM_GH_CLI_VERSION" = "latest" ]; then
        LATEST_TAG=$(curl url -s https://api.github.com/repos/cli/cli/releases/latest | jq -r '.tag_name')
        PARAM_GH_CLI_VERSION="${LATEST_TAG#v}"
    fi
    local download_url="https://github.com/cli/cli/releases/download/v${PARAM_GH_CLI_VERSION}/gh_${PARAM_GH_CLI_VERSION}_${platform}.${file_extension}"
    echo "Downloading the GitHub CLI from \"$download_url\"..."

    if ! curl -sSL "$download_url" -o "gh-cli.$file_extension"; then
        echo "Failed to download GH CLI from $download_url" >&2
        return 1
    fi
}
```

In particular, it seems that:
- `if [ "$PARAM_GH_CLI_VERSION" = "latest" ]` evaluates false
- as such, it tries to create a `download_url` with an empty or null `PARAM_GH_CLI_VERSION` 

What I tried so far:
- setting explicitly the `version` [parameter](https://circleci.com/developer/orbs/orb/circleci/github-cli#commands-install), even though it should be optional
- setting directly the  `PARAM_GH_CLI_VERSION` environment variable

In both cases the behaviour didn't change

## Expected behavior:

The `install` command should be able to download GH CLI

## Additional Information:

The same issue was reported [here](https://github.com/CircleCI-Public/github-cli-orb/issues/58) but it was closed without a fix

**Comment by marboledacci** [comment]
Does it work fine on 2.4? The issue you linked seems to be the same, but it was on 2.4

**Comment by patrickjholloway** [comment]
@tl-luca-baggi I am seeing this issue still on `2.6.2`
